name: Test Set Variable

# Hacky solution: https://stackoverflow.com/a/76439748
# Annoying that I have to do this for GitHub to show any action not on main

env:
  VERSION: 1.2.3.4
  RELEASE: 1.2

on:
  workflow_dispatch:
  pull_request:

jobs:
  test-set-variable:
    runs-on: ubuntu-latest
    steps:
      # Update repository variables for Conda package
      - name: Fake data for testing
        run: |
          touch PHGv2-v${{ env.RELEASE }}.tar
      - uses: action-pack/set-variable@v1
        with:
          name: 'PHG2_VERSION'
          value: '${{ env.VERSION }}'
          token: ${{secrets.PHGV2CD}}
      - name: Calculate MD5 of package
        run: |
          echo "PHG2_VERSION_MD5=$(md5sum PHGv2-v${{ env.RELEASE }}.tar)" >> $GITHUB_ENV
      - uses: action-pack/set-variable@v1
        with:
          name: 'PHG2_VERSION_MD5'
          value: '${{ env.PHG2_VERSION_MD5 }}'
          token: ${{secrets.PHGV2CD}}
